{
  "type": "record",
  "name": "UserEvent",
  "namespace": "com.hopoong.avro.user",
  "fields": [
    {"name": "id", "type": {"type": "string", "logicalType": "uuid"}},
    {"name": "tenant_id", "type": "string"},
    {"name": "user_id", "type": "string"},
    {"name": "session_id", "type": ["null", "string"], "default": null},
    {"name": "event_type", "type": "string"},
    {"name": "feature", "type": ["null", "string"], "default": null},
    {"name": "occurred_at", "type": {"type": "long", "logicalType": "timestamp-millis"}},
    {"name": "created_at", "type": {"type": "long", "logicalType": "timestamp-millis"}}
  ]
} 