
logging:
  config: classpath:logback/logback-spring.xml
  level:
    root: info


server:
  port: 9400


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/main_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    show-sql: false
  config:
    import: "optional:classpath:/application-core.yml"
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
      auto.register.schemas: true
      specific.avro.reader: true
    streams:
      application-id: audit-service-dev
    producer:
      acks: 1

elasticsearch:
  host: localhost
  port: 9200
  scheme: http

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true

# 선택: 공통 태그로 환경/앱 이름 부여(라벨 폭증 방지)
management.metrics.tags:
  app: resource-service
  component: db-writer