plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.1'
	id 'io.spring.dependency-management' version '1.1.5'

}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
	maven { url 'https://packages.confluent.io/maven/' }
}


dependencies {

	implementation project(':core-service')

	// springframework
	implementation 'org.springframework.boot:spring-boot-starter-web'		// web
	implementation 'org.springframework.boot:spring-boot-starter-actuator'	// actuator
	implementation("org.springframework.boot:spring-boot-starter-data-jpa")

	// PostgreSQL
	runtimeOnly("org.postgresql:postgresql")

	// hibernate-types
	implementation 'com.vladmihalcea:hibernate-types-52:2.20.0'

	// kafka
	implementation 'org.springframework.kafka:spring-kafka'
	implementation 'org.apache.kafka:kafka-streams'
	implementation 'io.confluent:kafka-avro-serializer:7.8.0'
	implementation "io.confluent:kafka-streams-avro-serde:7.8.0"

	// elasticsearch
	implementation 'co.elastic.clients:elasticsearch-java:8.12.0'
	implementation 'org.apache.httpcomponents.client5:httpclient5:5.2'
	implementation 'org.glassfish:jakarta.json:2.0.1'
	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.0'

	// redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// guava
	implementation 'com.google.guava:guava:33.3.1-jre'

	// prometheus
	implementation 'io.micrometer:micrometer-registry-prometheus'

	// test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
